edu_rover:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers

  knuckle_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: knuckle_1_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

  knuckle_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: knuckle_2_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}
  
  knuckle_3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: knuckle_3_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

  knuckle_4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: knuckle_4_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

  # Velocity Controllers

  wheel_1_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_1_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

  wheel_2_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_2_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

  wheel_3_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_3_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

  wheel_4_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_4_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}
  